version: "3.2"
services:
  app:
    build: .
    container_name: jok3r
    restart: always
    environment:
      - MIX_ENV=dev
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    tty: true
    stdin_open: true
