name: Verify Dialyzer

on:
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  dialyzer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.15.6]
        otp: [26.1.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v1
        id: mix-cache-dialyzer
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-cache-dialyzer.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: Check Dialyzer
        run: mix dialyzer